mod cli;
mod commands;
mod core;
mod error;
mod models;
mod workspace;

use anyhow::Result;
use clap::Parser;
use cli::{Cli, Commands};
use models::workspace_request::{Language, PackageManager, Stack, WorkspaceRequest};

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::New {
            path,
            name,
            lang,
            stack,
            pm,
            install,
            docker,
            git,
            tests,
            cuda,
        } => commands::new::run(build_request(
            path, name, lang, stack, pm, install, docker, git, tests, cuda,
        )?)?,
        Commands::Python {
            path,
            name,
            stack,
            pm,
            install,
            docker,
            git,
            tests,
            cuda,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Python,
            stack,
            pm,
            install,
            docker,
            git,
            tests,
            cuda,
        )?)?,
        Commands::Node {
            path,
            name,
            stack,
            pm,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            stack,
            pm,
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Go {
            path,
            name,
            stack,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Go,
            stack,
            Some(PackageManager::Go),
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Lua {
            path,
            name,
            stack,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Lua,
            stack,
            Some(PackageManager::Make),
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Hardhat {
            path,
            name,
            pm,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            Stack::Hardhat,
            pm,
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Express {
            path,
            name,
            pm,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            Stack::Express,
            pm,
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Flask {
            path,
            name,
            pm,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Python,
            Stack::Flask,
            pm,
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Django {
            path,
            name,
            pm,
            install,
            docker,
            git,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Python,
            Stack::Django,
            pm,
            install,
            docker,
            git,
            false,
            false,
        )?)?,
        Commands::Fastapi {
            path,
            name,
            pm,
            install,
            docker,
            git,
            tests,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Python,
            Stack::Fastapi,
            pm,
            install,
            docker,
            git,
            tests,
            false,
        )?)?,
        Commands::Huggingface {
            path,
            name,
            pm,
            install,
            docker,
            git,
            tests,
            cuda,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Python,
            Stack::Huggingface,
            pm,
            install,
            docker,
            git,
            tests,
            cuda,
        )?)?,
        Commands::Vite {
            path,
            name,
            pm,
            install,
            docker,
            git,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            Stack::Vite,
            pm,
            install,
            docker,
            git,
            false,
            false,
        )?)?,
        Commands::Nextjs {
            path,
            name,
            pm,
            install,
            docker,
            git,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            Stack::Nextjs,
            pm,
            install,
            docker,
            git,
            false,
            false,
        )?)?,
        Commands::Sveltekit {
            path,
            name,
            pm,
            install,
            docker,
            git,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Node,
            Stack::Sveltekit,
            pm,
            install,
            docker,
            git,
            false,
            false,
        )?)?,
        Commands::LlamaCpp {
            path,
            name,
            install,
            docker,
            git,
            cuda,
        } => commands::new::run(build_request(
            path,
            name,
            Language::Cpp,
            Stack::LlamaCpp,
            Some(PackageManager::Make),
            install,
            docker,
            git,
            false,
            cuda,
        )?)?,
        Commands::List => commands::list::run()?,
        Commands::Doctor => commands::doctor::run()?,
    }

    Ok(())
}

fn build_request(
    path: String,
    name: Option<String>,
    language: Language,
    stack: Stack,
    pm: Option<PackageManager>,
    install: bool,
    docker: bool,
    git: bool,
    tests: bool,
    cuda: bool,
) -> Result<WorkspaceRequest> {
    let package_manager =
        pm.unwrap_or_else(|| workspace::manager::default_package_manager(&language, &stack));

    WorkspaceRequest::from_cli(
        path,
        name,
        language,
        stack,
        package_manager,
        install,
        docker,
        git,
        tests,
        cuda,
    )
}
